apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
      --replicas=2
    kompose.version: 1.19.0 (30736a39)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-cache-service
  name: todo-cache-service
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
          --replicas=2
        kompose.version: 1.19.0 (30736a39)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-cache-service
    spec:
      containers:
      - env:
        - name: REDIS_HOST
        - name: REDIS_PORT
        image: gravitonian/todo-cache-service:1.0
        name: todo-cache-service
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "134217728"
      restartPolicy: Always
status: {}
