apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
      --replicas=2
    kompose.version: 1.19.0 (30736a39)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-view
  name: todo-view
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
          --replicas=2
        kompose.version: 1.19.0 (30736a39)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-view
    spec:
      containers:
      - image: gravitonian/todo-view:1.0
        name: todo-view
        ports:
        - containerPort: 4200
        - containerPort: 8080
        resources:
          limits:
            memory: "805306368"
        volumeMounts:
        - mountPath: /usr/src/app
          name: todo-view-claim0
        - mountPath: /usr/src/app/node-modules
          name: todo-view-claim1
      restartPolicy: Always
      volumes:
      - name: todo-view-claim0
        persistentVolumeClaim:
          claimName: todo-view-claim0
      - name: todo-view-claim1
        persistentVolumeClaim:
          claimName: todo-view-claim1
status: {}
