apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
      --replicas=2
    kompose.version: 1.19.0 (30736a39)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-proxy
  name: todo-proxy
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
          --replicas=2
        kompose.version: 1.19.0 (30736a39)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-proxy
    spec:
      containers:
      - image: gravitonian/todo-proxy:1.0
        name: todo-proxy
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "134217728"
      restartPolicy: Always
status: {}
