apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
      --replicas=2
    kompose.version: 1.19.0 (30736a39)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-postgres
  name: todo-postgres
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
          --replicas=2
        kompose.version: 1.19.0 (30736a39)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-postgres
    spec:
      containers:
      - image: gravitonian/todo-postgres:1.0
        name: todo-postgres
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "536870912"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      restartPolicy: Always
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
status: {}
