apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
      --replicas=2
    kompose.version: 1.19.0 (30736a39)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-rabbitmq
  name: todo-rabbitmq
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
          --replicas=2
        kompose.version: 1.19.0 (30736a39)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER
        image: rabbitmq:3.7.13-management
        name: todo-rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            memory: "209715200"
      restartPolicy: Always
status: {}
